In [1]:
#Phase 1: Data Cleaning
#What is the shape of the dataset?
import pandas as pd
df=pd.read_csv("/content/dataset.csv")
df.shape

(6097, 21)

In [2]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73.0,230666.0,False,0.676,0.4610,...,-6.746,0.0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4.0,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55.0,149610.0,False,0.420,0.1660,...,-17.235,1.0,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4.0,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57.0,210826.0,False,0.438,0.3590,...,-9.734,1.0,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4.0,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71.0,201933.0,False,0.266,0.0596,...,-18.515,1.0,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3.0,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82.0,198853.0,False,0.618,0.4430,...,-9.681,1.0,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4.0,acoustic

In [3]:
#What are the names of all columns?
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [4]:
#What is the data type of each column?
df.dtypes

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity          float64
duration_ms         float64
explicit             object
danceability        float64
energy              float64
key                 float64
loudness            float64
mode                float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature      float64
track_genre          object
dtype: object

In [5]:
#Which columns contain missing values?
#How many missing values are present in each column?

df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          1
duration_ms         1
explicit            1
danceability        1
energy              1
key                 1
loudness            1
mode                1
speechiness         1
acousticness        1
instrumentalness    1
liveness            1
valence             1
tempo               1
time_signature      1
track_genre         1
dtype: int64

In [6]:
#What percentage of missing values is present in each column?
df.isnull().sum()/len(df)*100

Unnamed: 0          0.000000
track_id            0.000000
artists             0.000000
album_name          0.000000
track_name          0.000000
popularity          0.016402
duration_ms         0.016402
explicit            0.016402
danceability        0.016402
energy              0.016402
key                 0.016402
loudness            0.016402
mode                0.016402
speechiness         0.016402
acousticness        0.016402
instrumentalness    0.016402
liveness            0.016402
valence             0.016402
tempo               0.016402
time_signature      0.016402
track_genre         0.016402
dtype: float64

In [7]:
#How will you handle the missing values?
df["artists"].fillna(df["artists"].mode()[0],inplace=True)
df["album_name"].fillna(df["album_name"].mode()[0],inplace=True)
df["track_name"].fillna(df["track_name"].mode()[0],inplace=True)

/tmp/ipykernel_484/81194766.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["artists"].fillna(df["artists"].mode()[0],inplace=True)
/tmp/ipykernel_484/81194766.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["album_name"].fillna(df["album_name"].mode()[0],inplace=True)
/tmp/ipykernel_484/81194766.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["track_name"].fillna(df["track_name"].mode()[0],inplace=True)

In [8]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          1
duration_ms         1
explicit            1
danceability        1
energy              1
key                 1
loudness            1
mode                1
speechiness         1
acousticness        1
instrumentalness    1
liveness            1
valence             1
tempo               1
time_signature      1
track_genre         1
dtype: int64

In [9]:
#Are there any duplicate records in the dataset?
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6092    False
6093    False
6094    False
6095    False
6096    False
Length: 6097, dtype: bool

In [10]:
#How many duplicate records are present?
df.duplicated().sum()

np.int64(0)

In [11]:
#Remove duplicate records and verify the result.
df.duplicated(subset=["Unnamed: 0"]).sum()

np.int64(0)

In [12]:
#Is the Unnamed: 0 column useful for analysis?
df['Unnamed: 0']
df.loc[0:5]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73.0,230666.0,False,0.676,0.4610,...,-6.746,0.0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4.0,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55.0,149610.0,False,0.420,0.1660,...,-17.235,1.0,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4.0,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57.0,210826.0,False,0.438,0.3590,...,-9.734,1.0,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4.0,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71.0,201933.0,False,0.266,0.0596,...,-18.515,1.0,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3.0,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82.0,198853.0,False,0.618,0.4430,...,-9.681,1.0,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4.0,acoustic
5,5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58.0,214240.0,False,0.688,0.4810,...,-8.807,1.0,0.1050,0.2890,0.000000,0.1890,0.666,98.017,4.0,acoustic

In [13]:
#Remove unnecessary columns from the dataset.
df.drop(columns=["Unnamed: 0"],axis=1,inplace=True)

In [14]:
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73.0,230666.0,False,0.676,0.4610,1.0,-6.746,0.0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4.0,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55.0,149610.0,False,0.420,0.1660,1.0,-17.235,1.0,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4.0,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57.0,210826.0,False,0.438,0.3590,0.0,-9.734,1.0,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4.0,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71.0,201933.0,False,0.266,0.0596,0.0,-18.515,1.0,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3.0,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82.0,198853.0,False,0.618,0.4430,2.0,-9.681,1.0,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4.0,acoustic

In [15]:
#How many unique values are present in each categorical column?
cat_col=['track_id', 'artists', 'album_name', 'track_name','track_genre']
df[cat_col].nunique()

track_id       5495
artists        1818
album_name     3210
track_name     4774
track_genre       7
dtype: int64

In [ ]:
#Are there any inconsistent values in categorical columns?

In [16]:
#Verify the final cleaned dataset shape.
df.shape

(6097, 20)

In [17]:
#Phase 2: Data Understanding
#How many songs are available in the dataset?
df["track_genre"].value_counts()

track_genre
acoustic       1000
afrobeat       1000
alt-rock       1000
alternative    1000
ambient        1000
anime          1000
black-metal      96
Name: count, dtype: int64

In [18]:
#How many unique genres are available?
df["track_genre"].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', nan], dtype=object)

In [19]:

#How many unique artists are available?
df["artists"].unique()

array(['Gen Hoshino', 'Ben Woodward', 'Ingrid Michaelson;ZAYN', ...,
       "Old Man's Child", 'Darkthrone', 'Bölzer'], dtype=object)

In [20]:
#How many unique albums are available?
df["album_name"].unique()

array(['Comedy', 'Ghost (Acoustic)', 'To Begin Again', ...,
       'Live at the Opera', 'A Taste of Extreme Divinity', 'Passage'],
      dtype=object)

In [21]:
#What is the average song popularity?
df["popularity"].mean()

np.float64(36.30544619422572)

In [22]:
#What is the average song duration?
df["duration_ms"].mean()

np.float64(229667.84202755906)

In [23]:
#What is the average danceability score?
df["danceability"].mean()

np.float64(0.5329894520997376)

In [24]:
#What is the average energy score?
df["energy"].mean()

np.float64(0.5918471440288713)

In [25]:
#What is the average tempo of songs?
df["tempo"].mean()

np.float64(119.99148326771652)

In [26]:
#What is the average loudness of songs?
df["loudness"].mean()

np.float64(-9.291291502624672)

In [27]:
#Phase 3: Pivot Table Analysis
#Create a pivot table showing average popularity by genre.
pd.pivot_table(
    df,
    values="popularity",
    index="track_genre",
    aggfunc="mean"
)

             popularity
track_genre
acoustic      42.483000
afrobeat      24.399000
alt-rock      33.943000
alternative   24.337000
ambient       44.191000
anime         48.772000
black-metal   33.260417

In [28]:
#Create a pivot table showing average danceability by genre.
pd.pivot_table(
    df,
    values="danceability",
    index="track_genre",
    aggfunc="mean"
)

             danceability
track_genre
acoustic         0.549593
afrobeat         0.669580
alt-rock         0.534493
alternative      0.559927
ambient          0.367867
anime            0.537451
black-metal      0.314505

In [29]:
#Create a pivot table showing average energy by genre.
pd.pivot_table(
    df,
    values="energy",
    index="track_genre",
    aggfunc="mean"
)

               energy
track_genre
acoustic     0.435368
afrobeat     0.702812
alt-rock     0.754173
alternative  0.720030
ambient      0.237162
anime        0.674108
black-metal  0.877573

In [30]:
#Create a pivot table showing average valence by genre.
pd.pivot_table(
    df,
    values="valence",
    index="track_genre",
    aggfunc="mean"
)

              valence
track_genre
acoustic     0.424023
afrobeat     0.698619
alt-rock     0.518260
alternative  0.495570
ambient      0.167498
anime        0.434463
black-metal  0.226610

In [31]:
#Create a pivot table showing average loudness by genre.
pd.pivot_table(
    df,
    values="loudness",
    index="track_genre",
    aggfunc="mean"
)

              loudness
track_genre
acoustic     -9.447843
afrobeat     -7.789353
alt-rock     -6.191489
alternative  -6.078777
ambient     -18.601365
anime        -7.932289
black-metal  -6.235385

In [32]:
#Create a pivot table showing average tempo by genre.
pd.pivot_table(
    df,
    values="tempo",
    index="track_genre",
    aggfunc="mean"
)

                  tempo
track_genre
acoustic     119.010624
afrobeat     119.213337
alt-rock     124.634404
alternative  122.232394
ambient      111.113129
anime        123.529616
black-metal  122.235187

In [33]:
#Create a pivot table showing average duration by genre.
pd.pivot_table(
    df,
    values="duration_ms",
    index="track_genre",
    aggfunc="mean"
)

             duration_ms
track_genre
acoustic      214896.957
afrobeat      248412.791
alt-rock      235455.907
alternative   222016.180
ambient       237059.038
anime         210204.076
black-metal   333439.750

In [34]:
#Create a pivot table showing song count by genre